version: "3.8"

services:
  portefoljepilot:
    container_name: portefoljepilot
    build:
      context: /volume2/workspace/AI/AI-Active/AI-Python-PortefoeljePilot
      dockerfile: Dockerfile.prod
    ports:
      - "5050:5000"
    volumes:
      - /volume2/workspace/AI/AI-Active/AI-Python-PortefoeljePilot:/app
    restart: unless-stopped
    depends_on:
      - local-ai
  watchdog:
    build:
      context: /volume2/workspace/AI/AI-Active/AI-Python-PortefoeljePilot
      dockerfile: Dockerfile.dev
    command:
      [
        "watchmedo",
        "auto-restart",
        "--directory=.",
        "--pattern=*.py",
        "--recursive",
        "--",
        "python",
        "watchdog_runner.py",
      ]
    volumes:
      - /volume2/workspace/AI/AI-Active/AI-Python-PortefoeljePilot:/app
    depends_on:
      - portefoljepilot

  localai:
    image: ghcr.io/go-skynet/local-ai:latest
    container_name: localai
    ports:
      - "1234:8080"
    volumes:
      - /volume2/workspace/AI/models:/models
    environment:
      - MODELS_PATH=/models
      - DEBUG=true
      - THREADS=4
      - CONTEXT_SIZE=4096
