services:
  portefoljepilot:
    container_name: portefoljepilot
    labels:
      cockpit.role: "CV-agent"
      cockpit.weight: "medium"
    build:
      context: ./ # Lokalt projektmappe
      dockerfile: Dockerfile.prod
    ports:
      - "5050:5000"
    volumes:
      - Z:\:/app
    restart: unless-stopped
    depends_on:
      - localai

  watchdog:
    container_name: watchdog
    labels:
      cockpit.role: "watchdog"
      cockpit.weight: "low"
    build:
      context: ./ # Samme lokale mappe
      dockerfile: Dockerfile.dev
    command:
      [
        "watchmedo",
        "auto-restart",
        "--directory=.",
        "--pattern=*.py",
        "--recursive",
        "--",
        "python",
        "watchdog_runner.py",
      ]
    volumes:
      - Z:\:/app
    depends_on:
      - portefoljepilot
    restart: unless-stopped

  localai:
    container_name: localai
    labels:
      cockpit.role: "AI-agent"
      cockpit.weight: "high"
    image: localai/localai:latest
    ports:
      - "1234:8080"
    volumes:
      - Z:\models:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - MODELS_PATH=/models
      - DEBUG=false
      - THREADS=4
      - CONTEXT_SIZE=2048
    restart: unless-stopped
