services:
  portefoljepilot:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - FLASK_PORT=5050
    #command: ["python", "run.py"]
